### ISSUE TITLE
[feature request] add node discovery for dukto mode

### ISSUE THREAD

**Issue by mo-han** [liuyug/ndrop#3]
it's noticed current version doesn't auto discover nodes in LAN in dukto mode
packet capturing proves that
it's better to add it
i'd like to make a PR but i'm still struggling to understand your code
if you could take the job it would be much more efficient since it's written by you

**Comment by liuyug** [comment]
It will auto discovery other nodes if all node are in the same subnetwork.
Please check your node ip address, netmask and firewall.

**Comment by mo-han** [comment]
weird, on my laptop, ndrop doesn't send out broadcast packet, while on my desktop computer, it does.

**Comment by liuyug** [comment]
Do you think what we talk?
the protocol of both ndrop and dukto is the same. ndrop is not smart to identify your laptop or desktop.

What are your machine's IP address, netmask and broadcast address? I think you have a strange network configuration or adapter.

**Comment by mo-han** [comment]
geez, i'm using dukto itself on my laptop just fine, if it's the network problem then dukto should suffer the same issue.
please don't assume people being incapable of exclusive method.

**Comment by liuyug** [comment]
check your firewall and broadcast address that is x.x.x.255 or other.

auto discovery is the base feature. It work well in my testing environment.

**Comment by liuyug** [comment]
python3 -c "import netifaces;print(([netifaces.ifaddresses(ifname) for ifname in netifaces.interfaces()]))"

python3 -c "from ndrop.transport import get_broadcast_address; print(get_broadcast_address())"

结果给我

**Comment by mo-han** [comment]
There will be a PR.
